[package]
name = "rusterize"
version = "0.1.0"
authors = ["Hyde46 <denis.heid@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
