name: Rust

on: 
  push:
    branches:
    - master
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./rusterize/
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./rusterize/
      run: cargo test --verbose
